import express from 'express'
import cors from 'cors'
import dotenv from 'dotenv'

const app= express()
app.use(cors())
dotenv.config()

app.get('/',(req,res)=>{
    res.send("Hello this is backend and my name is sohan  ")
})
app.get('/api/jokes',(req,res)=>{
    const jokes=[
         { id: 1, title: "Smart Refrigerator", date: "2025-12-05", joke: "My fridge is running… I guess I should go catch it!" },
  { id: 2, title: "Math Problem", date: "2025-12-05", joke: "Why was the equal sign so humble? Because he knew he wasn’t less or greater than anyone." },
  { id: 3, title: "Computer Joke", date: "2025-12-05", joke: "Why did the computer get cold? It forgot to close its Windows!" },
  { id: 4, title: "Library Issue", date: "2025-12-05", joke: "I asked the librarian if the library had books on paranoia. She whispered, 'They’re right behind you…'" },
  { id: 5, title: "Ghost Problem", date: "2025-12-05", joke: "Why don’t ghosts lie? Because you can see right through them!" },
  { id: 6, title: "Lazy Dog", date: "2025-12-05", joke: "I told my dog to fetch a stick. He said, 'You threw it, YOU get it.'" },
  { id: 7, title: "Broken Pencil", date: "2025-12-05", joke: "I tried writing with a broken pencil. It was pointless." },
  { id: 8, title: "Traffic Light", date: "2025-12-05", joke: "Why did the traffic light turn red? You would too if everyone stared at you while changing!" },
  { id: 9, title: "Sleep Problem", date: "2025-12-05", joke: "I’m great at multitasking. I can waste time, be unproductive, and procrastinate all at once!" },
  { id: 10, title: "Elevator Joke", date: "2025-12-05", joke: "I don’t trust elevators. They always seem to be up to something." },
  { id: 11, title: "Time Travel", date: "2025-12-05", joke: "I tried to time travel earlier… but I got caught in traffic." },
  { id: 12, title: "Forgetful Brain", date: "2025-12-05", joke: "My brain is like the Bermuda Triangle—information goes in and is never found again." },
  { id: 13, title: "Coffee Joke", date: "2025-12-05", joke: "Why did the coffee file a police report? It got mugged." },
  { id: 14, title: "Phone Joke", date: "2025-12-05", joke: "Why don’t smartphones go to school? They already have too many 'classes.' " },
  { id: 15, title: "Bicycle", date: "2025-12-05", joke: "Why did the bicycle fall over? It was two-tired." },
  { id: 16, title: "Shoes Joke", date: "2025-12-05", joke: "I bought new shoes from a drug dealer. I don’t know what he laced them with, but I’ve been tripping all day!" },
  { id: 17, title: "Ocean Joke", date: "2025-12-05", joke: "What did the ocean say to the beach? Nothing, it just waved." },
  { id: 18, title: "Egg Joke", date: "2025-12-05", joke: "Why don’t eggs tell jokes? They’d crack each other up!" },
  { id: 19, title: "Stairs", date: "2025-12-05", joke: "I don’t trust stairs. They're always up to something or going down." },
  { id: 20, title: "Music Joke", date: "2025-12-05", joke: "Why did the musician bring a ladder to the concert? Because the notes were too high!" },
  { id: 21, title: "Cat Nap", date: "2025-12-05", joke: "Why don’t cats play poker in the jungle? Too many cheetahs!" },
  { id: 22, title: "Library Silence", date: "2025-12-05", joke: "Why did the book go to the doctor? It had too many chapters missing." },
  { id: 23, title: "Chicken", date: "2025-12-05", joke: "Why did the chicken join a band? Because it had the drumsticks!" },
  { id: 24, title: "Piano Joke", date: "2025-12-05", joke: "Why did the piano break up with the accordion? Too many keys to handle." },
  { id: 25, title: "Calendar", date: "2025-12-05", joke: "Why did the calendar go to therapy? Its days were numbered." },
  { id: 26, title: "Sandwich", date: "2025-12-05", joke: "Why did the sandwich go to the party? Because it was on a roll!" },
  { id: 27, title: "Battery Joke", date: "2025-12-05", joke: "Why did the battery go to school? To get a little charged up!" },
  { id: 28, title: "Math Joke", date: "2025-12-05", joke: "Why was the fraction nervous about marrying the decimal? Because he would have to convert." },
  { id: 29, title: "Scarecrow", date: "2025-12-05", joke: "Why did the scarecrow win an award? He was outstanding in his field." },
  { id: 30, title: "Cookie Joke", date: "2025-12-05", joke: "Why did the cookie go to the hospital? Because it felt crummy!" },
  { id: 31, title: "Internet Joke", date: "2025-12-05", joke: "Why don’t websites get cold? They use cookies to keep warm." },
  { id: 32, title: "Money Joke", date: "2025-12-05", joke: "Why did the man put his money in the freezer? He wanted cold hard cash!" },
  { id: 33, title: "Gym Joke", date: "2025-12-05", joke: "Why don’t some couples go to the gym? Because some relationships don’t work out." },
  { id: 34, title: "Ice Cream", date: "2025-12-05", joke: "Why did the ice cream truck break down? Because of the rocky road!" },
  { id: 35, title: "Dog Joke", date: "2025-12-05", joke: "Why did the dog sit in the shade? Because he didn’t want to be a hot dog!" },
  { id: 36, title: "Moon Joke", date: "2025-12-05", joke: "Why did the moon skip dinner? It was full." },
  { id: 37, title: "Chair Joke", date: "2025-12-05", joke: "Why did the chair go to therapy? It felt unseated." },
  { id: 38, title: "Pen Joke", date: "2025-12-05", joke: "Why did the pen break up with the pencil? It found someone sharper." },
  { id: 39, title: "Beer Joke", date: "2025-12-05", joke: "Why did the beer file a police report? It got mugged." },
  { id: 40, title: "Weather Joke", date: "2025-12-05", joke: "Why did the storm go to school? To improve its thunderstanding." },
  { id: 41, title: "Clock Joke", date: "2025-12-05", joke: "Why did the clock get kicked out of class? It tocked too much." },
  { id: 42, title: "Elephant Joke", date: "2025-12-05", joke: "Why do elephants never use computers? They're afraid of the mouse." },
  { id: 43, title: "Vegetable Joke", date: "2025-12-05", joke: "Why did the tomato turn red? Because it saw the salad dressing!" },
  { id: 44, title: "Banana Joke", date: "2025-12-05", joke: "Why did the banana go to the doctor? Because it wasn’t peeling well." },
  { id: 45, title: "Teacher Joke", date: "2025-12-05", joke: "Why did the teacher go to the beach? To test the waters." },
  { id: 46, title: "Shoe Joke", date: "2025-12-05", joke: "Why did the shoe go to school? To get a little laced up knowledge." },
  { id: 47, title: "Penguin Joke", date: "2025-12-05", joke: "Why don’t penguins like talking to strangers at parties? They find it ice-breaking." },
  { id: 48, title: "Cow Joke", date: "2025-12-05", joke: "Why did the cow go to outer space? To see the moooon!" },
  { id: 49, title: "Laptop Joke", date: "2025-12-05", joke: "Why did the laptop go to art school? To improve its sketching skills." },
  { id: 50, title: "Bread Joke", date: "2025-12-05", joke: "Why did the loaf of bread break up? It found someone butter." },
  { id: 51, title: "Fish Joke", date: "2025-12-05", joke: "Why don’t fish like basketball? They’re afraid of the net." },
  { id: 52, title: "Robot Joke", date: "2025-12-05", joke: "Why did the robot go on a diet? It had too many bytes." },
  { id: 53, title: "Moonlight", date: "2025-12-05", joke: "Why did the moon go to therapy? It was feeling a little eclipsed." },
  { id: 54, title: "Car Joke", date: "2025-12-05", joke: "Why did the car apply for a job? It wanted to drive success." },
  { id: 55, title: "Bird Joke", date: "2025-12-05", joke: "Why do birds fly south in winter? Because it’s faster than walking!" },
  { id: 56, title: "Star Joke", date: "2025-12-05", joke: "Why did the star go to school? To get brighter." },
  { id: 57, title: "Laptop Battery", date: "2025-12-05", joke: "Why was the laptop tired? It lost its charge." },
  { id: 58, title: "Lamp Joke", date: "2025-12-05", joke: "Why did the lamp break up? It couldn’t handle the spotlight." },
  { id: 59, title: "Coffee Shop", date: "2025-12-05", joke: "Why did the coffee file a police report? It got mugged." },
  { id: 60, title: "Candy Joke", date: "2025-12-05", joke: "Why did the candy go to school? To become a Smartie!" },
  { id: 61, title: "Phone Charger", date: "2025-12-05", joke: "Why did the phone charger break up? It wasn’t connecting anymore." },
  { id: 62, title: "Door Joke", date: "2025-12-05", joke: "Why did the door go to school? To improve its swing." },
  { id: 63, title: "Book Joke", date: "2025-12-05", joke: "Why did the book go to school? To improve its sentence structure." },
  { id: 64, title: "Pencil Joke", date: "2025-12-05", joke: "Why was the pencil sad? Because it felt pointless." },
  { id: 65, title: "Music Joke", date: "2025-12-05", joke: "Why did the musician get locked out? He forgot the keys." },
  { id: 66, title: "Dog Bone", date: "2025-12-05", joke: "Why did the dog bury the bone? He wanted to keep it for later." },
  { id: 67, title: "Ice Cube", date: "2025-12-05", joke: "Why did the ice cube refuse to fight? It didn’t want to crack under pressure." },
  { id: 68, title: "Paint Joke", date: "2025-12-05", joke: "Why did the paint go to school? To brush up on its skills." },
  { id: 69, title: "Chocolate Joke", date: "2025-12-05", joke: "Why did the chocolate go to the party? It was a sweet occasion." },
  { id: 70, title: "Coffee Mug", date: "2025-12-05", joke: "Why did the coffee mug get promoted? Because it was steaming ahead." },
  { id: 71, title: "Window Joke", date: "2025-12-05", joke: "Why did the window break up? It couldn’t handle the pressure." },
  { id: 72, title: "Chair Joke", date: "2025-12-05", joke: "Why did the chair feel depressed? It felt sat upon." },
  { id: 73, title: "Planet Joke", date: "2025-12-05", joke: "Why did the planet go to school? To get a little orbit-ducation." },
  { id: 74, title: "Apple Joke", date: "2025-12-05", joke: "Why did the apple stop in the middle of the road? Because it ran out of juice." },
  { id: 75, title: "Camera Joke", date: "2025-12-05", joke: "Why did the camera go to school? To focus on its goals." },
  { id: 76, title: "Elephant Joke", date: "2025-12-05", joke: "Why don’t elephants use computers? They’re afraid of the mouse." },
  { id: 77, title: "Carrot Joke", date: "2025-12-05", joke: "Why did the carrot get an award? It was outstanding in its field." },
  { id: 78, title: "Moon Joke", date: "2025-12-05", joke: "Why did the moon go to school? To be a little brighter." },
  { id: 79, title: "Bread Joke", date: "2025-12-05", joke: "Why did the bread go to the doctor? It felt crumby." },
  { id: 80, title: "Socks Joke", date: "2025-12-05", joke: "Why did the sock go to school? To get a little footed knowledge." },
  { id: 81, title: "Tiger Joke", date: "2025-12-05", joke: "Why don’t tigers play poker? Too many cheetahs." },
  { id: 82, title: "Rain Joke", date: "2025-12-05", joke: "Why did the rain go to school? To improve its precipitation." },
  { id: 83, title: "Bird Joke", date: "2025-12-05", joke: "Why did the bird go to school? To improve its tweet skills." },
  { id: 84, title: "Pizza Joke", date: "2025-12-05", joke: "Why did the pizza go to school? To get a little slice of knowledge." },
  { id: 85, title: "Butter Joke", date: "2025-12-05", joke: "Why did the butter go to the doctor? It was feeling spread thin." },
  { id: 86, title: "Cake Joke", date: "2025-12-05", joke: "Why did the cake go to school? To become a smart cake!" },
  { id: 87, title: "Sun Joke", date: "2025-12-05", joke: "Why did the sun go to school? To get a little brighter." },
  { id: 88, title: "Hat Joke", date: "2025-12-05", joke: "Why did the hat go to school? To top it off." },
  { id: 89, title: "Milk Joke", date: "2025-12-05", joke: "Why did the milk go to school? To become cultured." },
  { id: 90, title: "Cat Joke", date: "2025-12-05", joke: "Why did the cat sit on the computer? It wanted to keep an eye on the mouse." },
  { id: 91, title: "Dog Joke", date: "2025-12-05", joke: "Why did the dog sit in the shade? Because he didn’t want to be a hot dog!" },
  { id: 92, title: "Tree Joke", date: "2025-12-05", joke: "Why did the tree go to school? To branch out." },
  { id: 93, title: "Horse Joke", date: "2025-12-05", joke: "Why did the horse go behind the tree? To change its jockeys." },
  { id: 94, title: "Rabbit Joke", date: "2025-12-05", joke: "Why did the rabbit go to school? To improve its hare-itage." },
  { id: 95, title: "Balloon Joke", date: "2025-12-05", joke: "Why did the balloon go to school? To get a little inflated knowledge." },
    ]
    res.send(jokes)
})
app.listen(3000,()=>{
    console.log('Server is running at the port 3000')
})